#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------
#use Time::HiRes qw(usleep);
#use Env qw(BLOCK_INSTANCE); 
#
playerctl metadata xesam:artist
echo -n " - "
playerctl metadata xesam:title

# sub buttons {
#  if ($ENV{'BLOCK_BUTTON'} == 1) {
#             system("playerctl play-pause");
#         } elsif ($ENV{'BLOCK_BUTTON'} == 3) {
#             system("playerctl next");
#         } elsif ($ENV{'BLOCK_BUTTON'} == 4) {
#             system("playerctl volume 0.01+");
#         } elsif ($ENV{'BLOCK_BUTTON'} == 5) {
#             system("playerctl volume 0.01-");
#         }   
# }
# case $BLOCK_BUTTON in
#     1) playerctl play-pause ;;
#     4) playerctl previous;;
#     5) playerctl next
# esac